# Generated by Django 4.2.3 on 2023-07-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_users_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Password',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
