# Generated by Django 4.2.3 on 2023-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Users_gender',
            field=models.CharField(default='male', max_length=6),
        ),
    ]
