# Generated by Django 4.2.3 on 2023-07-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_datas',
            name='hd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='t_datas',
            name='td',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(default='12345', max_length=200),
        ),
    ]
